### ISSUE TITLE
Unlocalized in b3 messages

### ISSUE THREAD

**Issue by wkuzma** [D4edalus/CoD4x_Server#47] opened 2016-08-20 19:01 UTC
UNLOCALIZED[Server:message]
the unlocalized is shown in red
in cod4 there are no [ ] bracketing the message 

I get the unlocalized in the message when I use rcons say function 
on the cod4x server and I do not get unlocalized  on just a cod4 server.

I am using the windows version of cod4x

**Comment by florczakraf** [comment] 2016-08-20 19:42
This is not related to b3 at all so please remove the b3 parts in this report.
1. What version of server do you use? If not the latest, then please try to run revision 3ea0939d52d8ea34fa3781e427ca40c689d6b6a5 (since the baa14820b36f2be33bd5b1735c67be162cd5ce2b) is broken.
2. What language are your server files? (Go to `<cod4root>/zone`, there should be directory with language name.)
3. Are you running any modifications on the server?
* Mods?
* Custom _.gsc_s/_.gsx_s in `<cod4root>/main_shared` directory?
* Any additional _.iwd_s in <cod4root>/main` directory?
* Any additional _.ff_s in `<cod4root>/zone/<language>` directory?

Note: Parts of directories that are between angle brackets are meta names, you should match them with your own setup.

**Comment by T-Maxxx** [comment] 2016-08-20 20:34
@florczakraf Don't worry its well-known client-specific problem (maybe not for 1.7 players).
@wkuzma You need to disable localization warnings on client. Dvar "loc_warnings" set to 0. If you want to disable warnings for all players, you'll have to add `.gsc` script with `player setClientDvar("loc_warnings", 0);`

**Comment by florczakraf** [comment] 2016-08-20 21:01
Ow, thanks for letting me know :smirk:.

**Comment by wkuzma** [comment] 2016-08-21 00:41
1. What version of server do you use? If not the latest, then please try to run revision 3ea0939 (since the baa1482) is broken.
I am running COD4 X win_mingw-x86 build 1059 dec 21 2015

2. What language are your server files? 
English language

3. Are you running any modifications on the server?
    Mods?
    Custom .gscs/.gsxs in <cod4root>/main_shared directory?
    Any additional .iwds in <cod4root>/main directory?
   Any additional .ffs in <cod4root>/zone/<language> directory?

None of the above

**Comment by D4edalus** [comment] 2016-08-21 20:35
how can this be reproduced ?

**Comment by wkuzma** [comment] 2016-08-22 01:57
I get the unlocalized in the message when I use rcons say function
on the cod4x server and I do not get unlocalized on just a cod4 server.

**Comment by T-Maxxx** [comment] 2016-08-22 05:02
@D4edalus Set "loc_warnings" to 1 on client and say something through server console. Or use `rcon say` command.

**Comment by T-Maxxx** [comment] 2016-09-04 08:58
I think this issue can be closed since there's no bugs but common debugging practice.
![1](https://cloud.githubusercontent.com/assets/7836454/18229984/d440c656-7296-11e6-8246-ffab2099b66e.png)
![2](https://cloud.githubusercontent.com/assets/7836454/18229983/d43bcf0c-7296-11e6-8381-716ffa2a76fa.png)

**Comment by D4edalus** [comment] 2016-09-04 11:50
setClientDvar("loc_warnings", 0); goes into the scripts of a server owner
to disable it for your client locally type into console: \loc_warnings 0

closed as this is a problem specific to the individual client. maybe some b3 scripts turn that flag on for clients, but that is a problem of b3 then. or maybe OP has downloaded a cfg which turned on the flag.

**Closed by D4edalus** 2016-09-04 11:50 UTC
Labels: bug

**Comment by wkuzma** [comment] 2016-09-05 05:53
I understand that cod4x is a fairly new patch for cod4 and also understand that tere are thing that we would just have to live with. maybe someone can show me how to add a script with setClientDvar("loc_warnings", 0) I do not know how to add scripts to my server.
as for B3 it was not running at all in one of the tests that was done on this 
just rcon was used to show the words
